"""
exec_dbt_api
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum


@aql.dataframe(task_id="python_1")
def python_1_func():
    DAG auto-generated by Astro Cloud IDE.
    """
    
    from airflow.decorators import dag
    from airflow.providers.dbt.cloud.operators.dbt import DbtCloudRunJobOperator
    from datetime import datetime
    
    
    default_args={
        "owner": "Charmine Azajar (AZR),Open in Cloud IDE",
    }
    
    @dag(
        default_args=default_args,
        schedule="0 0 * * *",
        start_date=datetime(2024,10,21),
        catchup=False,
        owner_links={
            "Charmine Azajar (AZR)": "mailto:azr-azajc0@sapowernetworks.onmicrosoft.com",
            "Open in Cloud IDE": "https://cloud.astronomer.io/cm28anj6y0o3w01oqhrbmwzez/cloud-ide/cm2cdz64009hd01n3mqmfqn2p/cm2iueepb18ta01m19i62tc3c",
        },
    )
    def execute_dbt_cloud_poc():
        dbt_cloud_run_job_operator_1 = DbtCloudRunJobOperator(
            dbt_cloud_conn_id="snowflake_conn_astroproj_poc",
            job_id=25371,
            account_id=195,
            timeout=600,
            task_id="dbt_cloud_run_job_operator_1",
        )
    
    dag_obj = execute_dbt_cloud_poc()
    

default_args={
    "owner": "Charmine Azajar (AZR),Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 * * * *",
    start_date=pendulum.from_format("2024-10-22", "YYYY-MM-DD").in_tz("Australia/Adelaide"),
    catchup=False,
    owner_links={
        "Charmine Azajar (AZR)": "mailto:azr-azajc0@sapowernetworks.onmicrosoft.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/cm28anj6y0o3w01oqhrbmwzez/cloud-ide/cm2cdz64009hd01n3mqmfqn2p/cm2jlt1kk1dvc01mg4fuigy8p",
    },
)
def exec_dbt_api():
    python_1 = python_1_func()

dag_obj = exec_dbt_api()
