"""
execute_dbt_cloud_poc
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from airflow.providers.dbt.cloud.operators.dbt import DbtCloudRunJobOperator
import pendulum


default_args={
    "owner": "Charmine Azajar (AZR),Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2024-10-21", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Charmine Azajar (AZR)": "mailto:azr-azajc0@sapowernetworks.onmicrosoft.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/cm28anj6y0o3w01oqhrbmwzez/cloud-ide/cm2cdz64009hd01n3mqmfqn2p/cm2iueepb18ta01m19i62tc3c",
    },
)
def execute_dbt_cloud_poc():
    dbt_cloud_run_job_operator_1 = DbtCloudRunJobOperator(
        job_id=25371,
        task_id="dbt_cloud_run_job_operator_1",
    )

dag_obj = execute_dbt_cloud_poc()
